-- Merge the five overlapping article ideas into their existing principles, then insert the seven distinct rules.
INSERT OR IGNORE INTO revisions(id,content_id,version,snapshot_json,action,actor,created_at) SELECT 'dedupe-20261003/regles/01-ne-jamais-decider-sous-pression',id,version,draft_json,'merge','migration',strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM content WHERE id='regles/01-ne-jamais-decider-sous-pression' AND version=1 AND updated_by='migration';
UPDATE content SET draft_json=json_set(draft_json,'$.detail','Lorsqu''une personne, un message ou un site vous pousse à décider immédiatement, ralentissez volontairement. Vérifiez l''information par un autre canal et accordez-vous quelques minutes avant toute action irréversible.

« Paiement immédiat », « compte bientôt bloqué » ou « dernier avertissement » cherchent parfois à déclencher une réaction avant la réflexion. Une urgence peut être réelle, mais elle ne doit jamais supprimer la vérification.

Le bon réflexe : si une demande vous presse, faites une pause, relisez-la et contrôlez son origine avant de répondre, payer ou cliquer.

Règle d''Or : Plus une demande vous pousse à agir vite, plus vous devez prendre le temps de la vérifier.'), published_json=CASE WHEN published_json IS NULL THEN NULL ELSE json_set(published_json,'$.detail','Lorsqu''une personne, un message ou un site vous pousse à décider immédiatement, ralentissez volontairement. Vérifiez l''information par un autre canal et accordez-vous quelques minutes avant toute action irréversible.

« Paiement immédiat », « compte bientôt bloqué » ou « dernier avertissement » cherchent parfois à déclencher une réaction avant la réflexion. Une urgence peut être réelle, mais elle ne doit jamais supprimer la vérification.

Le bon réflexe : si une demande vous presse, faites une pause, relisez-la et contrôlez son origine avant de répondre, payer ou cliquer.

Règle d''Or : Plus une demande vous pousse à agir vite, plus vous devez prendre le temps de la vérifier.') END, version=version+1, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'), updated_by='migration', last_change='Merged editorial text into an existing equivalent rule.' WHERE id='regles/01-ne-jamais-decider-sous-pression' AND version=1 AND updated_by='migration';
INSERT OR IGNORE INTO revisions(id,content_id,version,snapshot_json,action,actor,created_at) SELECT 'dedupe-20261003/regles/02-verifiez-l-identite-avant-de-faire-confiance',id,version,draft_json,'merge','migration',strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM content WHERE id='regles/02-verifiez-l-identite-avant-de-faire-confiance' AND version=1 AND updated_by='migration';
UPDATE content SET draft_json=json_set(draft_json,'$.detail','Avant de transmettre une information sensible, de payer ou de modifier un accès, utilisez un moyen indépendant pour confirmer que vous parlez bien à la bonne personne ou à la bonne organisation.

Une signature, un logo, des couleurs familières ou un ton professionnel peuvent être reproduits. Un message qui semble venir d''un collègue, d''un fournisseur, d''une banque ou d''une administration n''est donc pas automatiquement authentique. Pour une demande d''argent, de coordonnées ou d''information sensible, répondre au message ne suffit pas.

Le bon réflexe : confirmez la demande par un numéro habituel ou un contact officiel dont vous connaissiez déjà les coordonnées.

Règle d''Or : Une demande inhabituelle doit toujours être vérifiée par un autre canal.'), published_json=CASE WHEN published_json IS NULL THEN NULL ELSE json_set(published_json,'$.detail','Avant de transmettre une information sensible, de payer ou de modifier un accès, utilisez un moyen indépendant pour confirmer que vous parlez bien à la bonne personne ou à la bonne organisation.

Une signature, un logo, des couleurs familières ou un ton professionnel peuvent être reproduits. Un message qui semble venir d''un collègue, d''un fournisseur, d''une banque ou d''une administration n''est donc pas automatiquement authentique. Pour une demande d''argent, de coordonnées ou d''information sensible, répondre au message ne suffit pas.

Le bon réflexe : confirmez la demande par un numéro habituel ou un contact officiel dont vous connaissiez déjà les coordonnées.

Règle d''Or : Une demande inhabituelle doit toujours être vérifiée par un autre canal.') END, version=version+1, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'), updated_by='migration', last_change='Merged editorial text into an existing equivalent rule.' WHERE id='regles/02-verifiez-l-identite-avant-de-faire-confiance' AND version=1 AND updated_by='migration';
INSERT OR IGNORE INTO revisions(id,content_id,version,snapshot_json,action,actor,created_at) SELECT 'dedupe-20261003/regles/17-verifiez-toute-information-importante-produite-par-une-ia',id,version,draft_json,'merge','migration',strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM content WHERE id='regles/17-verifiez-toute-information-importante-produite-par-une-ia' AND version=1 AND updated_by='migration';
UPDATE content SET draft_json=json_set(draft_json,'$.detail','Pour une décision importante, vérifiez les chiffres, dates, citations et affirmations auprès d''une source fiable avant de les utiliser. Une IA peut mélanger des informations, inventer une référence, mal interpréter un document ou présenter une réponse dépassée, même si son texte paraît assuré.

Le bon réflexe : utilisez l''IA pour chercher ou réfléchir, puis contrôlez les faits importants auprès de sources fiables.

Règle d''Or : Une réponse d''IA n''est pas une preuve : vérifiez toujours ce qui compte.'), published_json=CASE WHEN published_json IS NULL THEN NULL ELSE json_set(published_json,'$.detail','Pour une décision importante, vérifiez les chiffres, dates, citations et affirmations auprès d''une source fiable avant de les utiliser. Une IA peut mélanger des informations, inventer une référence, mal interpréter un document ou présenter une réponse dépassée, même si son texte paraît assuré.

Le bon réflexe : utilisez l''IA pour chercher ou réfléchir, puis contrôlez les faits importants auprès de sources fiables.

Règle d''Or : Une réponse d''IA n''est pas une preuve : vérifiez toujours ce qui compte.') END, version=version+1, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'), updated_by='migration', last_change='Merged editorial text into an existing equivalent rule.' WHERE id='regles/17-verifiez-toute-information-importante-produite-par-une-ia' AND version=1 AND updated_by='migration';
INSERT OR IGNORE INTO revisions(id,content_id,version,snapshot_json,action,actor,created_at) SELECT 'dedupe-20261003/regles/18-ne-confiez-pas-a-une-ia-ce-que-vous-ne-publieriez-pas',id,version,draft_json,'merge','migration',strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM content WHERE id='regles/18-ne-confiez-pas-a-une-ia-ce-que-vous-ne-publieriez-pas' AND version=1 AND updated_by='migration';
UPDATE content SET draft_json=json_set(draft_json,'$.detail','Avant de transmettre un document, un secret commercial ou une information personnelle, vérifiez les conditions du service et supprimez les éléments inutiles. Les contrats, les données clients, les informations bancaires ou les secrets professionnels peuvent avoir des conséquences importantes s''ils sortent de leur environnement prévu.

Le bon réflexe : vérifiez les règles de confidentialité du service et demandez-vous si vous pourriez confier cette information à un tiers.

Règle d''Or : Une IA ne doit jamais devenir le coffre-fort de données que vous n''auriez pas le droit de partager.'), published_json=CASE WHEN published_json IS NULL THEN NULL ELSE json_set(published_json,'$.detail','Avant de transmettre un document, un secret commercial ou une information personnelle, vérifiez les conditions du service et supprimez les éléments inutiles. Les contrats, les données clients, les informations bancaires ou les secrets professionnels peuvent avoir des conséquences importantes s''ils sortent de leur environnement prévu.

Le bon réflexe : vérifiez les règles de confidentialité du service et demandez-vous si vous pourriez confier cette information à un tiers.

Règle d''Or : Une IA ne doit jamais devenir le coffre-fort de données que vous n''auriez pas le droit de partager.') END, version=version+1, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'), updated_by='migration', last_change='Merged editorial text into an existing equivalent rule.' WHERE id='regles/18-ne-confiez-pas-a-une-ia-ce-que-vous-ne-publieriez-pas' AND version=1 AND updated_by='migration';
INSERT OR IGNORE INTO content(id,draft_json,published_json,version,updated_at,updated_by,last_change) VALUES('regles/76-un-mot-de-passe-visible-est-deja-un-mot-de-passe-compromis','{"id":76,"number":"76","slug":"76-un-mot-de-passe-visible-est-deja-un-mot-de-passe-compromis","title":"Un mot de passe visible est déjà un mot de passe compromis.","summary":"Un secret aperçu dans une photo, une capture ou un document partagé ne l''est plus.","detail":"Un post-it posé sur un bureau, une capture d''écran, une photo publiée en ligne ou un document partagé peuvent révéler un mot de passe sans aucune attaque informatique. Le risque augmente encore si ce secret est réutilisé sur plusieurs services.\n\nLe bon réflexe : considérez comme compromis tout mot de passe vu par une autre personne. Remplacez-le et utilisez un secret différent pour chaque service important.\n\nRègle d''Or : Un mot de passe visible est déjà un mot de passe compromis.","categoryId":"cybersecurite","order":75,"subcategory":"","homeRank":0}','{"id":76,"number":"76","slug":"76-un-mot-de-passe-visible-est-deja-un-mot-de-passe-compromis","title":"Un mot de passe visible est déjà un mot de passe compromis.","summary":"Un secret aperçu dans une photo, une capture ou un document partagé ne l''est plus.","detail":"Un post-it posé sur un bureau, une capture d''écran, une photo publiée en ligne ou un document partagé peuvent révéler un mot de passe sans aucune attaque informatique. Le risque augmente encore si ce secret est réutilisé sur plusieurs services.\n\nLe bon réflexe : considérez comme compromis tout mot de passe vu par une autre personne. Remplacez-le et utilisez un secret différent pour chaque service important.\n\nRègle d''Or : Un mot de passe visible est déjà un mot de passe compromis.","categoryId":"cybersecurite","order":75,"subcategory":"","homeRank":0}',1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),'migration','');
INSERT OR IGNORE INTO revisions(id,content_id,version,snapshot_json,action,actor,created_at) VALUES('initial/regles/76-un-mot-de-passe-visible-est-deja-un-mot-de-passe-compromis','regles/76-un-mot-de-passe-visible-est-deja-un-mot-de-passe-compromis',1,'{"id":76,"number":"76","slug":"76-un-mot-de-passe-visible-est-deja-un-mot-de-passe-compromis","title":"Un mot de passe visible est déjà un mot de passe compromis.","summary":"Un secret aperçu dans une photo, une capture ou un document partagé ne l''est plus.","detail":"Un post-it posé sur un bureau, une capture d''écran, une photo publiée en ligne ou un document partagé peuvent révéler un mot de passe sans aucune attaque informatique. Le risque augmente encore si ce secret est réutilisé sur plusieurs services.\n\nLe bon réflexe : considérez comme compromis tout mot de passe vu par une autre personne. Remplacez-le et utilisez un secret différent pour chaque service important.\n\nRègle d''Or : Un mot de passe visible est déjà un mot de passe compromis.","categoryId":"cybersecurite","order":75,"subcategory":"","homeRank":0}','migration','migration',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO content(id,draft_json,published_json,version,updated_at,updated_by,last_change) VALUES('regles/77-un-qr-code-n-est-pas-un-lien-de-confiance','{"id":77,"number":"77","slug":"77-un-qr-code-n-est-pas-un-lien-de-confiance","title":"Un QR Code n''est pas un lien de confiance.","summary":"Son apparence ne garantit pas que sa destination est sûre.","detail":"Un QR Code peut renvoyer vers un site légitime ou vers une imitation conçue pour récupérer un mot de passe ou des coordonnées bancaires. L''adresse réelle est souvent moins visible qu''un lien classique.\n\nLe bon réflexe : vérifiez la destination avant de vous connecter ou de transmettre la moindre information.\n\nRègle d''Or : Un QR Code n''est pas un lien de confiance : vérifiez sa destination avant de l''ouvrir.","categoryId":"cybersecurite","order":76,"subcategory":"","homeRank":0}','{"id":77,"number":"77","slug":"77-un-qr-code-n-est-pas-un-lien-de-confiance","title":"Un QR Code n''est pas un lien de confiance.","summary":"Son apparence ne garantit pas que sa destination est sûre.","detail":"Un QR Code peut renvoyer vers un site légitime ou vers une imitation conçue pour récupérer un mot de passe ou des coordonnées bancaires. L''adresse réelle est souvent moins visible qu''un lien classique.\n\nLe bon réflexe : vérifiez la destination avant de vous connecter ou de transmettre la moindre information.\n\nRègle d''Or : Un QR Code n''est pas un lien de confiance : vérifiez sa destination avant de l''ouvrir.","categoryId":"cybersecurite","order":76,"subcategory":"","homeRank":0}',1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),'migration','');
INSERT OR IGNORE INTO revisions(id,content_id,version,snapshot_json,action,actor,created_at) VALUES('initial/regles/77-un-qr-code-n-est-pas-un-lien-de-confiance','regles/77-un-qr-code-n-est-pas-un-lien-de-confiance',1,'{"id":77,"number":"77","slug":"77-un-qr-code-n-est-pas-un-lien-de-confiance","title":"Un QR Code n''est pas un lien de confiance.","summary":"Son apparence ne garantit pas que sa destination est sûre.","detail":"Un QR Code peut renvoyer vers un site légitime ou vers une imitation conçue pour récupérer un mot de passe ou des coordonnées bancaires. L''adresse réelle est souvent moins visible qu''un lien classique.\n\nLe bon réflexe : vérifiez la destination avant de vous connecter ou de transmettre la moindre information.\n\nRègle d''Or : Un QR Code n''est pas un lien de confiance : vérifiez sa destination avant de l''ouvrir.","categoryId":"cybersecurite","order":76,"subcategory":"","homeRank":0}','migration','migration',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO content(id,draft_json,published_json,version,updated_at,updated_by,last_change) VALUES('regles/78-ne-collez-pas-une-commande-que-vous-ne-comprenez-pas','{"id":78,"number":"78","slug":"78-ne-collez-pas-une-commande-que-vous-ne-comprenez-pas","title":"Ne collez pas une commande que vous ne comprenez pas.","summary":"Une commande peut modifier vos fichiers ou transmettre des informations.","detail":"Une commande ou un script présenté comme une solution rapide peut installer un programme, modifier des fichiers ou transmettre des informations sans que vous le remarquiez. Une présentation sérieuse ne garantit pas son innocuité.\n\nLe bon réflexe : comprenez ce que fait une commande et vérifiez sa provenance avant de l''exécuter. En cas de doute, ne l''exécutez pas.\n\nRègle d''Or : Ne collez jamais une commande trouvée sur Internet dans votre terminal sans savoir exactement ce qu''elle fait.","categoryId":"cybersecurite","order":77,"subcategory":"","homeRank":0}','{"id":78,"number":"78","slug":"78-ne-collez-pas-une-commande-que-vous-ne-comprenez-pas","title":"Ne collez pas une commande que vous ne comprenez pas.","summary":"Une commande peut modifier vos fichiers ou transmettre des informations.","detail":"Une commande ou un script présenté comme une solution rapide peut installer un programme, modifier des fichiers ou transmettre des informations sans que vous le remarquiez. Une présentation sérieuse ne garantit pas son innocuité.\n\nLe bon réflexe : comprenez ce que fait une commande et vérifiez sa provenance avant de l''exécuter. En cas de doute, ne l''exécutez pas.\n\nRègle d''Or : Ne collez jamais une commande trouvée sur Internet dans votre terminal sans savoir exactement ce qu''elle fait.","categoryId":"cybersecurite","order":77,"subcategory":"","homeRank":0}',1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),'migration','');
INSERT OR IGNORE INTO revisions(id,content_id,version,snapshot_json,action,actor,created_at) VALUES('initial/regles/78-ne-collez-pas-une-commande-que-vous-ne-comprenez-pas','regles/78-ne-collez-pas-une-commande-que-vous-ne-comprenez-pas',1,'{"id":78,"number":"78","slug":"78-ne-collez-pas-une-commande-que-vous-ne-comprenez-pas","title":"Ne collez pas une commande que vous ne comprenez pas.","summary":"Une commande peut modifier vos fichiers ou transmettre des informations.","detail":"Une commande ou un script présenté comme une solution rapide peut installer un programme, modifier des fichiers ou transmettre des informations sans que vous le remarquiez. Une présentation sérieuse ne garantit pas son innocuité.\n\nLe bon réflexe : comprenez ce que fait une commande et vérifiez sa provenance avant de l''exécuter. En cas de doute, ne l''exécutez pas.\n\nRègle d''Or : Ne collez jamais une commande trouvée sur Internet dans votre terminal sans savoir exactement ce qu''elle fait.","categoryId":"cybersecurite","order":77,"subcategory":"","homeRank":0}','migration','migration',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO content(id,draft_json,published_json,version,updated_at,updated_by,last_change) VALUES('regles/79-une-donnee-qui-a-fuite-doit-etre-consideree-comme-compromise','{"id":79,"number":"79","slug":"79-une-donnee-qui-a-fuite-doit-etre-consideree-comme-compromise","title":"Une donnée qui a fuité doit être considérée comme compromise.","summary":"Une donnée divulguée peut être recoupée et réutilisée bien plus tard.","detail":"Une adresse e-mail, un numéro de téléphone ou une ancienne information personnelle peuvent être associés à d''autres données et réutilisés longtemps après l''incident. Une donnée sortie de votre contrôle ne peut plus être considérée comme secrète.\n\nLe bon réflexe : après une fuite, remplacez les informations qui peuvent l''être et restez attentif aux messages, appels et tentatives de connexion inhabituels.\n\nRègle d''Or : Une donnée qui a fuité doit être considérée comme compromise.","categoryId":"cybersecurite","order":78,"subcategory":"","homeRank":0}','{"id":79,"number":"79","slug":"79-une-donnee-qui-a-fuite-doit-etre-consideree-comme-compromise","title":"Une donnée qui a fuité doit être considérée comme compromise.","summary":"Une donnée divulguée peut être recoupée et réutilisée bien plus tard.","detail":"Une adresse e-mail, un numéro de téléphone ou une ancienne information personnelle peuvent être associés à d''autres données et réutilisés longtemps après l''incident. Une donnée sortie de votre contrôle ne peut plus être considérée comme secrète.\n\nLe bon réflexe : après une fuite, remplacez les informations qui peuvent l''être et restez attentif aux messages, appels et tentatives de connexion inhabituels.\n\nRègle d''Or : Une donnée qui a fuité doit être considérée comme compromise.","categoryId":"cybersecurite","order":78,"subcategory":"","homeRank":0}',1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),'migration','');
INSERT OR IGNORE INTO revisions(id,content_id,version,snapshot_json,action,actor,created_at) VALUES('initial/regles/79-une-donnee-qui-a-fuite-doit-etre-consideree-comme-compromise','regles/79-une-donnee-qui-a-fuite-doit-etre-consideree-comme-compromise',1,'{"id":79,"number":"79","slug":"79-une-donnee-qui-a-fuite-doit-etre-consideree-comme-compromise","title":"Une donnée qui a fuité doit être considérée comme compromise.","summary":"Une donnée divulguée peut être recoupée et réutilisée bien plus tard.","detail":"Une adresse e-mail, un numéro de téléphone ou une ancienne information personnelle peuvent être associés à d''autres données et réutilisés longtemps après l''incident. Une donnée sortie de votre contrôle ne peut plus être considérée comme secrète.\n\nLe bon réflexe : après une fuite, remplacez les informations qui peuvent l''être et restez attentif aux messages, appels et tentatives de connexion inhabituels.\n\nRègle d''Or : Une donnée qui a fuité doit être considérée comme compromise.","categoryId":"cybersecurite","order":78,"subcategory":"","homeRank":0}','migration','migration',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO content(id,draft_json,published_json,version,updated_at,updated_by,last_change) VALUES('regles/80-une-sauvegarde-jamais-restauree-n-est-qu-une-promesse','{"id":80,"number":"80","slug":"80-une-sauvegarde-jamais-restauree-n-est-qu-une-promesse","title":"Une sauvegarde jamais restaurée n''est qu''une promesse.","summary":"Seule une restauration permet de savoir si vos fichiers sont récupérables.","detail":"Un disque peut être défectueux, une archive corrompue ou une sauvegarde rendue inaccessible par une attaque. Un statut « réussi » ne prouve pas que vos fichiers pourront être récupérés.\n\nLe bon réflexe : restaurez régulièrement quelques fichiers et vérifiez qu''ils sont bien utilisables.\n\nRègle d''Or : Une sauvegarde jamais restaurée n''est qu''une promesse.","categoryId":"cybersecurite","order":79,"subcategory":"","homeRank":0}','{"id":80,"number":"80","slug":"80-une-sauvegarde-jamais-restauree-n-est-qu-une-promesse","title":"Une sauvegarde jamais restaurée n''est qu''une promesse.","summary":"Seule une restauration permet de savoir si vos fichiers sont récupérables.","detail":"Un disque peut être défectueux, une archive corrompue ou une sauvegarde rendue inaccessible par une attaque. Un statut « réussi » ne prouve pas que vos fichiers pourront être récupérés.\n\nLe bon réflexe : restaurez régulièrement quelques fichiers et vérifiez qu''ils sont bien utilisables.\n\nRègle d''Or : Une sauvegarde jamais restaurée n''est qu''une promesse.","categoryId":"cybersecurite","order":79,"subcategory":"","homeRank":0}',1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),'migration','');
INSERT OR IGNORE INTO revisions(id,content_id,version,snapshot_json,action,actor,created_at) VALUES('initial/regles/80-une-sauvegarde-jamais-restauree-n-est-qu-une-promesse','regles/80-une-sauvegarde-jamais-restauree-n-est-qu-une-promesse',1,'{"id":80,"number":"80","slug":"80-une-sauvegarde-jamais-restauree-n-est-qu-une-promesse","title":"Une sauvegarde jamais restaurée n''est qu''une promesse.","summary":"Seule une restauration permet de savoir si vos fichiers sont récupérables.","detail":"Un disque peut être défectueux, une archive corrompue ou une sauvegarde rendue inaccessible par une attaque. Un statut « réussi » ne prouve pas que vos fichiers pourront être récupérés.\n\nLe bon réflexe : restaurez régulièrement quelques fichiers et vérifiez qu''ils sont bien utilisables.\n\nRègle d''Or : Une sauvegarde jamais restaurée n''est qu''une promesse.","categoryId":"cybersecurite","order":79,"subcategory":"","homeRank":0}','migration','migration',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO content(id,draft_json,published_json,version,updated_at,updated_by,last_change) VALUES('regles/81-une-information-anodine-peut-devenir-sensible-une-fois-recoupee','{"id":81,"number":"81","slug":"81-une-information-anodine-peut-devenir-sensible-une-fois-recoupee","title":"Une information anodine peut devenir sensible une fois recoupée.","summary":"Des détails publiés séparément peuvent révéler bien plus une fois réunis.","detail":"Votre prénom, votre ville, votre métier, une photo ou le nom de votre entreprise peuvent sembler inoffensifs pris séparément. Associés, ces détails peuvent révéler vos habitudes, vos relations ou votre lieu de travail et faciliter une tentative de manipulation.\n\nLe bon réflexe : avant de publier, pensez à ce qu''une personne pourrait déduire en combinant cette information avec tout ce qui est déjà accessible.\n\nRègle d''Or : Une information anodine seule peut devenir sensible une fois recoupée avec d''autres.","categoryId":"cybersecurite","order":80,"subcategory":"","homeRank":0}','{"id":81,"number":"81","slug":"81-une-information-anodine-peut-devenir-sensible-une-fois-recoupee","title":"Une information anodine peut devenir sensible une fois recoupée.","summary":"Des détails publiés séparément peuvent révéler bien plus une fois réunis.","detail":"Votre prénom, votre ville, votre métier, une photo ou le nom de votre entreprise peuvent sembler inoffensifs pris séparément. Associés, ces détails peuvent révéler vos habitudes, vos relations ou votre lieu de travail et faciliter une tentative de manipulation.\n\nLe bon réflexe : avant de publier, pensez à ce qu''une personne pourrait déduire en combinant cette information avec tout ce qui est déjà accessible.\n\nRègle d''Or : Une information anodine seule peut devenir sensible une fois recoupée avec d''autres.","categoryId":"cybersecurite","order":80,"subcategory":"","homeRank":0}',1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),'migration','');
INSERT OR IGNORE INTO revisions(id,content_id,version,snapshot_json,action,actor,created_at) VALUES('initial/regles/81-une-information-anodine-peut-devenir-sensible-une-fois-recoupee','regles/81-une-information-anodine-peut-devenir-sensible-une-fois-recoupee',1,'{"id":81,"number":"81","slug":"81-une-information-anodine-peut-devenir-sensible-une-fois-recoupee","title":"Une information anodine peut devenir sensible une fois recoupée.","summary":"Des détails publiés séparément peuvent révéler bien plus une fois réunis.","detail":"Votre prénom, votre ville, votre métier, une photo ou le nom de votre entreprise peuvent sembler inoffensifs pris séparément. Associés, ces détails peuvent révéler vos habitudes, vos relations ou votre lieu de travail et faciliter une tentative de manipulation.\n\nLe bon réflexe : avant de publier, pensez à ce qu''une personne pourrait déduire en combinant cette information avec tout ce qui est déjà accessible.\n\nRègle d''Or : Une information anodine seule peut devenir sensible une fois recoupée avec d''autres.","categoryId":"cybersecurite","order":80,"subcategory":"","homeRank":0}','migration','migration',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO content(id,draft_json,published_json,version,updated_at,updated_by,last_change) VALUES('regles/82-avant-de-transmettre-une-donnee-personnelle-verifiez-qu-elle-est-necessaire','{"id":82,"number":"82","slug":"82-avant-de-transmettre-une-donnee-personnelle-verifiez-qu-elle-est-necessaire","title":"Avant de transmettre une donnée personnelle, vérifiez qu''elle est nécessaire.","summary":"Un formulaire qui demande une information ne prouve pas qu''elle est indispensable.","detail":"Une date de naissance, une adresse, un numéro de téléphone ou une copie de document peuvent être conservés, recoupés ou compromis. Le fait qu''un champ existe ne signifie pas que vous devez le remplir.\n\nLe bon réflexe : demandez-vous à quoi sert la donnée et si le service en a réellement besoin avant de la transmettre.\n\nRègle d''Or : Avant de transmettre une donnée personnelle, demandez-vous si le service en a réellement besoin.","categoryId":"ia-numerique","order":81,"subcategory":"","homeRank":0}','{"id":82,"number":"82","slug":"82-avant-de-transmettre-une-donnee-personnelle-verifiez-qu-elle-est-necessaire","title":"Avant de transmettre une donnée personnelle, vérifiez qu''elle est nécessaire.","summary":"Un formulaire qui demande une information ne prouve pas qu''elle est indispensable.","detail":"Une date de naissance, une adresse, un numéro de téléphone ou une copie de document peuvent être conservés, recoupés ou compromis. Le fait qu''un champ existe ne signifie pas que vous devez le remplir.\n\nLe bon réflexe : demandez-vous à quoi sert la donnée et si le service en a réellement besoin avant de la transmettre.\n\nRègle d''Or : Avant de transmettre une donnée personnelle, demandez-vous si le service en a réellement besoin.","categoryId":"ia-numerique","order":81,"subcategory":"","homeRank":0}',1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),'migration','');
INSERT OR IGNORE INTO revisions(id,content_id,version,snapshot_json,action,actor,created_at) VALUES('initial/regles/82-avant-de-transmettre-une-donnee-personnelle-verifiez-qu-elle-est-necessaire','regles/82-avant-de-transmettre-une-donnee-personnelle-verifiez-qu-elle-est-necessaire',1,'{"id":82,"number":"82","slug":"82-avant-de-transmettre-une-donnee-personnelle-verifiez-qu-elle-est-necessaire","title":"Avant de transmettre une donnée personnelle, vérifiez qu''elle est nécessaire.","summary":"Un formulaire qui demande une information ne prouve pas qu''elle est indispensable.","detail":"Une date de naissance, une adresse, un numéro de téléphone ou une copie de document peuvent être conservés, recoupés ou compromis. Le fait qu''un champ existe ne signifie pas que vous devez le remplir.\n\nLe bon réflexe : demandez-vous à quoi sert la donnée et si le service en a réellement besoin avant de la transmettre.\n\nRègle d''Or : Avant de transmettre une donnée personnelle, demandez-vous si le service en a réellement besoin.","categoryId":"ia-numerique","order":81,"subcategory":"","homeRank":0}','migration','migration',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
